# Generated by Django 4.2.7 on 2024-01-11 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='approvals.customuser')),
                ('staff_id', models.CharField(max_length=20, null=True, unique=True)),
                ('department', models.CharField(choices=[('ELECTRICAL', 'Electrical and Electronics Engineering'), ('MECHANICAL', 'Mechanical Engineering'), ('ELECTRONICS', 'Electronics and Communications Engineering'), ('COMPUTER', 'Computer Science Engineering'), ('CIVIL', 'Civil Engineering'), ('CHEMICAL', 'Chemical Engineering'), ('IT', 'Information Technology'), ('AI', 'Artificial Intelligence'), ('CDS', 'Computational and Data Science')], max_length=100, null=True)),
                ('role', models.CharField(choices=[('MIS', 'MIS Officer'), ('HOD', 'Head of Department'), ('DEAN', 'Dean')], max_length=30, null=True)),
            ],
            bases=('approvals.customuser',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='approvals.customuser')),
                ('student_id', models.CharField(max_length=20, null=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('department', models.CharField(choices=[('ELECTRICAL', 'Electrical and Electronics Engineering'), ('MECHANICAL', 'Mechanical Engineering'), ('ELECTRONICS', 'Electronics and Communications Engineering'), ('COMPUTER', 'Computer Science Engineering'), ('CIVIL', 'Civil Engineering'), ('CHEMICAL', 'Chemical Engineering'), ('IT', 'Information Technology'), ('AI', 'Artificial Intelligence'), ('CDS', 'Computational and Data Science')], max_length=100, null=True)),
                ('program_type', models.CharField(choices=[('BACHELOR', 'Bachelors'), ('MASTER', 'Masters'), ('PHD', 'PhD')], max_length=100)),
            ],
            bases=('approvals.customuser',),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('response', models.TextField(max_length=500, null=True)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting for approval'), ('APPROVED', 'Approved')], max_length=20, null=True)),
                ('participants', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='approvals.customuser')),
                ('template_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='approvals.template')),
            ],
        ),
    ]
