# Generated by Django 4.2.7 on 2024-01-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_alter_template_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='participants',
            field=models.CharField(choices=[('1', 'MIS Officer'), ('2', 'Head of Department'), ('3', 'Dean')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('1', 'MIS Officer'), ('2', 'Head of Department'), ('3', 'Dean')], max_length=30, null=True),
        ),
    ]
