# Generated by Django 4.2.7 on 2024-01-12 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('approvals', '0004_template_participants_alter_employee_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='participants',
        ),
        migrations.AddField(
            model_name='request',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
