# Generated by Django 4.2.7 on 2024-01-12 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0005_remove_request_participants_request_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='template_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='approvals.template'),
        ),
    ]
