# Generated by Django 4.2.7 on 2024-01-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0007_alter_request_status_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Waiting for approval', 'Waiting for approval'), ('Approved by MIS Officer', 'Approved by MIS Officer'), ('Approved by Head of Department', 'Approved by Head of Department'), ('Approved by Dean', 'Approved by Dean')], default='Waiting for approval', max_length=100, null=True),
        ),
    ]
