# Generated by Django 4.2.7 on 2024-01-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0009_alter_request_template_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('1', 'MIS Officer'), ('2', 'Head of Department'), ('3', 'Dean')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='participants',
            field=models.CharField(choices=[('1', 'MIS Officer'), ('12', 'Head of Department'), ('123', 'Dean')], max_length=4, null=True),
        ),
    ]
